# Build artifactory for the App1 and deploy to GCP APP Engine.

steps:
- name: 'gcr.io/stg-sviridov/app_builder'
  args: [ 'dotnet', 'publish', '-c', 'Release' ]
  dir: 'App1'
  env: [ 'DOTNETPATH=App1' ]

- name: 'gcr.io/cloud-builders/gcloud'
  args: [ 'app', 'deploy', '/workspace/App1/bin/Release/netcoreapp2.1/publish/', '--stop-previous-version' ]
  env: [ 'DOTNETPATH=App1' ]
  timeout: 20m

artifacts:
  objects:
    location: 'gs://stg-sviridov/App1'
    paths: [ '/workspace/App1/bin/Release/netcoreapp2.1/publish/*' ]
