# Cloud builder for the App1 builder.

steps:
- name: 'gcr.io/cloud-builders/dotnet'
  args: [ 'publish', '-c', 'Release' ]
  dir: 'App1'
  env: [ 'DOTNETPATH=App1' ]

- name: 'gcr.io/cloud-builders/gcloud'
  args: [ 'app', 'deploy', '/workspace/App1/bin/Release/netcoreapp2.1/publish/', '--stop-previous-version', '-v=20' ]
  env: [ 'DOTNETPATH=App1' ]

artifacts:
  objects:
    location: 'gs://stg-sviridov/App1'
    paths: [ '/workspace/App1/bin/Release/netcoreapp2.1/publish/*' ]
